const BUY_MAX_RETRIES = 300;
const BUY_RETRY_DELAY = 250;
const BUY_TIME_CHECK_INTERVAL = 499;
const MAX_SLIPPAGE = 5;
const SELL_MAX_RETRIES = 1;
const USDC_TOKEN_ADDRESS = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';

export {
    BUY_RETRY_DELAY,
    BUY_TIME_CHECK_INTERVAL,
    BUY_MAX_RETRIES,
    MAX_SLIPPAGE,
    SELL_MAX_RETRIES,
    USDC_TOKEN_ADDRESS,
};
