const MAX_BUY_CONCURRENT_TRIES = 1;
const MAX_BUY_RETRIES = 1;
const MAX_SELL_RETRIES = 1;
const MAX_SLIPPAGE = 5;
const USDC_TOKEN_ADDRESS = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';

export {
    MAX_BUY_RETRIES,
    MAX_BUY_CONCURRENT_TRIES,
    MAX_SELL_RETRIES,
    MAX_SLIPPAGE,
    USDC_TOKEN_ADDRESS,
};
